apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-namespaced-habitat
  namespace: example-namespace
spec:
  # the core/nginx habitat service packaged as a Docker image
  image: kinvolk/nginx-hab
  count: 1
  service:
    name: nginx
    topology: standalone
    # if not present, defaults to "default"
    group: foobar
