apiVersion: habitat.sh/v1
kind: ServiceGroup
metadata:
  name: example-leader-follower-service-group
spec:
  # the core/consul habitat service packaged as a Docker image
  image: kinvolk/consul-hab
  # count must be at least 3 for a leader-follower topology
  count: 3
  habitat:
    topology: leader
    # if not present, defaults to "default"
    group: foobar
