apiVersion: v1
kind: Service
metadata:
  name: example-nodejs-service-group
spec:
  selector:
    service-group: example-nodejs-service-group
  type: NodePort
  ports:
  - name: web
    nodePort: 30001
    port: 5555
    protocol: TCP
  - name: http-gateway
    nodePort : 32767
    port: 9631
    protocol: TCP
