apiVersion: v1
kind: Secret
metadata:
  name: user-toml-secret
type: Opaque
data:
  # Each item needs to be encoded in base64, as Kubernetes
  # expects that encoding.
  # Plain text content: "message = 'Hello from our Habitat-Operator!'"
  user.toml: bWVzc2FnZSA9ICdIZWxsbyBmcm9tIG91ciBIYWJpdGF0LU9wZXJhdG9yISc=
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-configured-habitat
spec:
  image: kinvolk/nodejs-hab
  count: 1
  service:
    name: mytutorialapp
    topology: standalone
    group: nodejs
    # Create Secret with the initial configuration you want.
    configSecretName: user-toml-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mytutorialapp
spec:
  selector:
    habitat-name: example-configured-habitat
  type: NodePort
  ports:
  # This endpoint displays the message from the secret
  - name: web
    nodePort: 30001
    port: 5555
    protocol: TCP
  # This endpoint exposes the Habitat supervisor API
  - name: http-gateway
    nodePort : 32767
    port: 9631
    protocol: TCP
