{{- if .Values.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "habitat-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "habitat-operator.fullname" . }}
{{- end }}
