apiVersion: habitat.sh/v1
kind: ServiceGroup
metadata:
  name: example-standalone-service-group
spec:
  topology: standalone
  # the core/nginx habitat service packaged as a Docker image
  image: kinvolk/nginx-hab
  count: 1
