apiVersion: v1
kind: Secret
metadata:
  name: ring-key-20170816102049
  labels:
    habitat: "true"
    ring-key: "true"
type: Opaque
data:
  # base64-encoded ring key
  ring-key: U1lNLVNFQy0xCnJpbmcta2V5LTIwMTcwODE2MTAyMDQ5CgpyTmtKbkJxZHppVWdmdnYweEVhaWpzMWxHUGZUdHBLdFg0L0xaMmpQcWdJPQo=
---
apiVersion: habitat.sh/v1
kind: ServiceGroup
metadata:
  name: example-encrypted-service-group
spec:
  # the core/nginx habitat service packaged as a Docker image
  image: kinvolk/consul-hab
  count: 3
  habitat:
    topology: leader
    # the name of the secret containing the ring key
    ringKey: ring-key-20170816102049
